# Use the official Python 3.9 slim-buster image as the base image
FROM python:3.9-slim-buster

# Set the working directory for any RUN, CMD, ENTRYPOINT, COPY and ADD instructions that follow in the Dockerfile
WORKDIR /python-docker

EXPOSE 5000

COPY requirements.txt requirements.txt

RUN apt-get update && apt-get install ffmpeg libsm6 libxext6  -y
RUN pip3 install -r requirements.txt

VOLUME ["/python-docker/logs"]

COPY . .

CMD python3 -m flask run --host=0.0.0.0 --port=5000